services:
  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/thenrique395/investindoemnegociosweb:latest}
    ports:
      - "${FRONTEND_PORT:-4200}:4000"
    environment:
      PORT: 4000
      API_BASE_URL: ${API_BASE_URL:-http://35.174.50.187:5055/api/v1}
      ANGULAR_ALLOWED_HOSTS: ${ANGULAR_ALLOWED_HOSTS:-35.174.50.187:4201,35.174.50.187:4200,localhost:4200,localhost:4201}
    restart: unless-stopped
