services:
  frontend:
    build:
      context: ./investindoEmNegociosWeb
      dockerfile: Dockerfile
    container_name: investindo-frontend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      API_BASE_URL: http://35.174.50.187:5059/api/v1
