FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=4000
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY dist /app/dist
EXPOSE 4000
CMD ["node","dist/investindo-em-negocios-web/server/server.mjs"]
